# Generated by Django 5.2.7 on 2025-10-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_team_members_alter_team_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
    ]
